### ISSUE TITLE
Publish vscode-pink-candy to OPEN VSX

### ISSUE THREAD

**Issue by megatank58** [KubaP/vscode-pink-candy#11]
Hi there!

I had published your [extension (v1.3.5) to the open-vsx registry](https://open-vsx.org/extension/kuba-p/theme-pink-candy) 2 years ago under your namespace. The current extension is on v1.5.0. I realize I should have asked this before publishing but are you fine with me publishing or would you like to claim ownership of/take down the extension. 

## Context

Unfortunately, Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by KubaP** [comment]
Hi! That's cool honestly; I wouldn't have thought there would be enough interest to publish this extension to openvsx, but that's absolutely fine with me. I probably should care a bit more about people using non-microsoft vscode.

I think it'd be good to transfer ownership to me. I have a CI/CD workflow setup that automatically publishes to the Microsoft extension marketplace, so I could easily add a step to publish to the openvsx marketplace too. That way openvsx would always have the latest version automatically.

**Comment by megatank58** [comment]
That would be great, the instructions for claiming namespaces are given [here](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace)

Thank you very much for the awesome theme and for caring about non-microsoft vscode users.

**Comment by KubaP** [comment]
Glad you like the theme! I've requested ownership of the namespace at https://github.com/EclipseFdn/open-vsx.org/issues/2715#issue-2391395460 . Once that happens, I'll upload v1.5.0 as it currently stands.

**Comment by megatank58** [comment]
Thanks for your cooperation!

**Comment by klementineQt** [comment]
any update on this? :(

**Comment by KubaP** [comment]
Sorry, life got in the way :/

I've now had a bit of time so I've published the extension to openvsx proper. I've also just released an update that includes styling for new features and the ability to configure the terminal colour scheme.
