### ISSUE TITLE
Add border between activity bar and primary side bar

### ISSUE THREAD

**Issue by MiguelRipoll23** [KubaP/vscode-pink-candy#9]
I love the pink candy theme, using it at work all the time!

A border between the activity bar and primary side bar would look great to make this theme perfect.
Currently when the primary side bar is positioned at the left looks like this:

![image](https://github.com/KubaP/vscode-pink-candy/assets/3296866/286501ad-2609-4c99-acc3-573b474eacbd)

**Comment by KubaP** [comment]
Thanks for pointing this out! That is indeed a small inconsistency with the rest of the theme.

I'm planning on adding syntax highlighting for a few new languages, so I'll likely wait until I've done that so I can bundle all this into a single update. I'm planning on doing this relatively soon.

In the meantime, if you can't wait, you can add one of these snippets to your `settings.json`:
```json
"workbench.colorCustomizations": {
    // for light variant
    "activityBar.border": "#CECECE"

    // for dark variant
    "activityBar.border": "#3D434F"

    // for dark-warm variant
    "activityBar.border": "#504945"
}
```

**Comment by MiguelRipoll23** [comment]
Thank you!

**Comment by KubaP** [comment]
I've finally gotten round to releasing a new version 1.5.0 (2023-03-06) that, amongst other things, fixes this inconsistency. If you're still using this workaround you can remove it now.
